import type { LauncherConfig } from './config'

/** Minimal KEY=VALUE parser for tests/round-trips (ignores comments + blanks). */
export function parseEnv(text: string): Record<string, string> {
	const out: Record<string, string> = {}
	for (const raw of text.split('\n')) {
		const line = raw.trim()
		if (!line || line.startsWith('#')) continue
		const eq = line.indexOf('=')
		if (eq === -1) continue
		out[line.slice(0, eq)] = line.slice(eq + 1)
	}
	return out
}

/**
 * Render the .env the release compose (docker-compose.release.yml) expects. Keys mirror
 * .env.release.example exactly. Values are minted secrets / known ports — never user
 * free-text that needs quoting — so a plain KEY=VALUE form is safe.
 *
 * NOTE (launcher decision L-3): NO provider keys are written here. The LQ.AI stack boots
 * fully healthy with zero provider keys; the user adds OpenAI/Anthropic keys in-app via
 * Configure (BYOK, hot-applied with no restart) after first launch. The wizard collects
 * no provider secrets.
 */
export function renderEnv(cfg: LauncherConfig): string {
	const { secrets: s, ports: p } = cfg

	return [
		'# Generated by LQ.AI for Mac — do not edit by hand.',
		'',
		'# Image selection',
		`LQ_AI_IMAGE_TAG=${cfg.imageTag}`,
		`LQ_AI_IMAGE_NAMESPACE=${cfg.imageNamespace}`,
		'',
		'# Host ports (loopback-bound by the compose defaults)',
		`WEB_HOST_PORT=${p.web}`,
		`API_HOST_PORT=${p.api}`,
		`GATEWAY_HOST_PORT=${p.gateway}`,
		`POSTGRES_HOST_PORT=${p.postgres}`,
		`REDIS_HOST_PORT=${p.redis}`,
		`MINIO_API_HOST_PORT=${p.minioApi}`,
		`MINIO_CONSOLE_HOST_PORT=${p.minioConsole}`,
		'',
		'# Required backend secrets',
		'POSTGRES_DB=lq_ai',
		'POSTGRES_USER=lq_ai',
		`POSTGRES_PASSWORD=${s.POSTGRES_PASSWORD}`,
		'MINIO_ROOT_USER=lq_ai',
		`MINIO_ROOT_PASSWORD=${s.MINIO_ROOT_PASSWORD}`,
		'S3_ACCESS_KEY=lq_ai',
		`S3_SECRET_KEY=${s.S3_SECRET_KEY}`,
		`LQ_AI_GATEWAY_KEY=${s.LQ_AI_GATEWAY_KEY}`,
		`JWT_SECRET=${s.JWT_SECRET}`,
		''
	].join('\n')
}
